---
galaxy_info:
  author: "Samuel Camilo"
  description: "Atualiza OS em servidores com cPanel/DirectAdmin."
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["7", "8", "9"]
dependencies: []
